/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubes;

import Data.Data;
import Data.LinkListData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ASUS
 */
public class MenuDashboard extends javax.swing.JFrame {
     //inisialisasi objek data
    static Data dataMhs;
     DefaultTableModel model;
     /**Creates new form menuDashboard
     */
    public MenuDashboard(Data data) {
        initComponents();
        this.dataMhs = data; //mengisi objek dengan objek yang dikirim
        this.model = (DefaultTableModel)jTable1.getModel();
        
    }

    MenuDashboard(LinkListData data) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    public void reset(){
        //untuk mereset semua teks menjadi kosong
        txtNama.setText(null);
        txtNIK.setText(null);
        txtTTL.setText(null);
        txtEmail.setText(null);
        txtNomorPendaftaran.setText(null);
        txtAlamat.setText(null);
        comJenisKelamin.setSelectedItem(null);
    }
    
    public void editData(){
        // untuk mengedit data yang dipilih di row untuk dirubah
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1){
            if(jTable1.getSelectedRowCount()==0){
                JOptionPane.showMessageDialog(null, "Tidak ada data dalam tabel");
            }else{
                JOptionPane.showMessageDialog(null, "Pilih data yang akan diubah");
            }
        }else{
            model.setValueAt(txtNama.getText(), jTable1.getSelectedRow(), 0);
            model.setValueAt(txtNIK.getText(), jTable1.getSelectedRow(), 1);
            model.setValueAt(txtTTL.getText(), jTable1.getSelectedRow(), 2);
        }
    }
    
    public void deleteData(){
        //untuk menghapus data yang dipilih dirow
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1){
            if(jTable1.getSelectedRowCount()==0){
                JOptionPane.showMessageDialog(null, "Tidak ada data dalam tabel");
            }else{
                JOptionPane.showMessageDialog(null, "Pilih data yang akan diubah");
            }
        }else{
            model.removeRow(jTable1.getSelectedRow());
        }
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAbout = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        txtNIK = new javax.swing.JTextField();
        txtTTL = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtNomorPendaftaran = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        comJenisKelamin = new javax.swing.JComboBox<>();
        cari = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JLabel();
        btnEdit = new javax.swing.JLabel();
        btnHapus = new javax.swing.JLabel();
        btnReset = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel6.setText("jLabel6");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAbout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(240, 240, 240));
        btnAbout.setText("About");
        btnAbout.setToolTipText("");
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
        });
        jPanel1.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(240, 240, 240));
        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        txtNIK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtNIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 230, -1));

        txtTTL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtTTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 230, -1));

        txtAlamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 230, -1));

        txtNomorPendaftaran.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtNomorPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 230, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 230, -1));

        txtNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 230, -1));

        comJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "P" }));
        jPanel1.add(comJenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, -1, -1));

        cari.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        cari.setToolTipText("");
        cari.setBorder(null);
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        jPanel1.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 420, 30));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/Image/search_1.png"))); // NOI18N
        btnSearch.setText("jLabel2");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 170, 30, 40));

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(240, 240, 240));
        btnSimpan.setText("     Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 700, 110, 40));

        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(240, 240, 240));
        btnEdit.setText("      Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 700, 110, 40));

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(240, 240, 240));
        btnHapus.setText("     Hapus");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 700, 110, 40));

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(240, 240, 240));
        btnReset.setText("     Reset");
        btnReset.setToolTipText("");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 700, 110, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "NIK", "TTL", "Alamat", "Jenis Kelamin", "e-mail", "No. Pendaftaran"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 480, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/Image/menu.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1023, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        setVisible(false);
            new Login().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        //digunakan untuk mengadd data hjika kita mengklik tombol simpan
        if(txtNama.getText().equals("") ||txtNIK.getText().equals("") || txtTTL.getText().equals("") || txtAlamat.getText().equals("") || txtEmail.getText().equals("") || txtNomorPendaftaran.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data yang dimasukkan belum lengkap!");
        }
        else {
            
            //untuk membuat node
            
            LinkListData node = new LinkListData(txtNama.getText(),txtNIK.getText(),txtTTL.getText(),txtAlamat.getText(),txtEmail.getText(),comJenisKelamin.getItemAt(comJenisKelamin.getSelectedIndex()),txtEmail.getText(),txtNomorPendaftaran.getText());
            dataMhs.tambahData(node); // menggabungkan node yang baru saja dibuat
            model.addRow(new Object[]{txtNama.getText(),txtNIK.getText(),txtTTL.getText(),txtAlamat.getText(),comJenisKelamin.getItemAt(comJenisKelamin.getSelectedIndex()), txtEmail.getText(),txtNomorPendaftaran.getText()});
        }
        reset();
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        reset();
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        deleteData();// TODO add your handling code here:
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        editData();        
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        //fungsi code ini jika kita mengklik tombol about maka layar akan dipindahkan ke menu about
        setVisible(false);
         new MenuAbout(dataMhs).setVisible(true);
    }//GEN-LAST:event_btnAboutMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // fungsi ini adalah jika kita mengklik tombol search maka akan menampilkan data mahasiswa yang dicari
        LinkListData data = dataMhs.head; // awalan node
        boolean bool = false;
        //membuat looping sampai salah satu data = key maka boolean akan bernilai true dan looping akan berhenti
        while(data != null){
            if(cari.getText().equals(data.Nama)){
                bool = true;
                break;
            }
            data = data.next;
        }
        //pengecekan jika sudah di search atau data sudah ditemukan maka membuat object
        //baru data mahasiswa baru dan mengirimkan object data ke dalamnya.
        if(bool){
        new DataMahasiswaBaru(data).setVisible(true);
        
            bool = false;
        }
    }//GEN-LAST:event_btnSearchMouseClicked

    
    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
       
       
    }//GEN-LAST:event_cariActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDashboard(dataMhs).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAbout;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnHapus;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnReset;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel btnSimpan;
    private javax.swing.JTextField cari;
    private javax.swing.JComboBox<String> comJenisKelamin;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNIK;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNomorPendaftaran;
    private javax.swing.JTextField txtTTL;
    // End of variables declaration//GEN-END:variables
}
